<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="fastlane.lanes">
    
    
    
      
      <testcase classname="fastlane.lanes" name="0: cocoapods" time="11.426229">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="1: git_add" time="0.055749">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="2: git_commit" time="0.05026">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="3: push_to_git_remote" time="16.244595">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="4: git_tag_exists" time="0.013675">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="5: add_git_tag" time="0.019839">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="6: push_git_tags" time="11.036126">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="7: pod_push" time="233.818068">
        
          <failure message="/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/actions/actions_helper.rb:48:in `execute_action'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'&#10;Fastfile:54:in `block in parsing_binding'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/lane.rb:33:in `call'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:45:in `execute'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'&#10;/Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'&#10;/Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'&#10;/Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'&#10;/Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'&#10;/Library/Ruby/Gems/2.3.0/gems/fastlane-2.100.1/bin/fastlane:20:in `&lt;top (required)&gt;'&#10;/usr/local/bin/fastlane:22:in `load'&#10;/usr/local/bin/fastlane:22:in `&lt;main&gt;'&#10;&#10;Exit status of command 'pod trunk push 'JLXXNetWorking.podspec' --allow-warnings' was 1 instead of 0.&#10;Updating spec repo `master`&#10;Validating podspec&#10; -&gt; JLXXNetWorking -&gt; JLXXNetWorking (1.3.8)&#10;    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/local/bin/git clone https://github.com/cnsuer/JLXXNetWorking.git /var/folders/pg/vnxk1kl519z1ks1hddc4mr0h0000gn/T/d20180725-55351-lc4vva --template= --single-branch --depth 1 --branch 1.3.8&#10;&#10;Cloning into '/var/folders/pg/vnxk1kl519z1ks1hddc4mr0h0000gn/T/d20180725-55351-lc4vva'...&#10;warning: Could not find remote branch 1.3.8 to clone.&#10;fatal: Remote branch 1.3.8 not found in upstream origin&#10;) during validation.&#10;&#10;[!] The spec did not pass validation, due to 1 error.&#10;" />
        
      </testcase>
    
  </testsuite>
</testsuites>
